server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001

logging:
  loggers:
    io.cratekube: DEBUG
    org.reflections: ERROR

swagger:
  resourcePackage: io.cratekube.lifecycle.resources

jerseyClient:
  timeout: 5000ms
  gzipEnabledForRequests: false

auth:
  apiKeys:
    - name: admin
      key: ${ADMIN_APIKEY:-eknvDrmcDtseeieSMTvngo}
      roles: ['admin']

kubeconfigLocation: ${KUBE_CONFIG_LOCATION:-/app/kube/kubeconfig}

jobs:
  upgradeAvailabilityJob: ${UPGRADE_JOB_EXECUTION_FREQUENCY:-5min}
  componentDeploymentJob: ${DEPLOYMENT_JOB_EXECUTION_FREQUENCY:-5min}

github:
  orgHome: ${GITHUB_ORG_HOME:-https://github.com/cratekube}
  orgBaseRawHome: ${GITHUB_ORG_RAW_HOME:-https://raw.githubusercontent.com/cratekube}

# Used for global cache key, github queries and kubectl retrieval purposes.
# these keys coincide with both the repository names and the selector label names in each repositories deployment.yml.
# Boolean values represent whether we should deploy the latest version from github if the service is not in k8s.
managedComponents:
  cluster-mgmt-service: ${$CLUSTER_MGMT_ENABLED:-true}
  cloud-mgmt-service: ${$CLOUD_MGMT_ENABLED:-true}
  lifecycle-service: ${$LIFECYCLE_ENABLED:-true}

